name: 🔧 Upgrade Tracking
description: Track progress on ZeroTermux upgrades
title: "[UPGRADE] Phase X: Description"
labels: ["enhancement", "upgrade"]
body:
  - type: markdown
    attributes:
      value: |
        Use this template to track upgrade progress for ZeroTermux.
        See [UPGRADE_SUMMARY.md](../../UPGRADE_SUMMARY.md) for the complete upgrade plan.
        
  - type: dropdown
    id: phase
    attributes:
      label: Upgrade Phase
      description: Which phase of the upgrade does this track?
      options:
        - Phase 1 - Critical Security Fixes (Week 1)
        - Phase 2 - Build System Updates (Week 2)
        - Phase 3 - Android API Updates (Week 3-4)
        - Phase 4 - Dependency Updates (Week 5)
        - Phase 5 - Code Quality (Week 6)
        - Phase 6 - CI/CD Improvements (Week 7)
    validations:
      required: true
      
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: What is the priority level?
      options:
        - 🔴 Critical
        - 🟠 High
        - 🟡 Medium
        - 🟢 Low
    validations:
      required: true
      
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What needs to be done in this phase?
      placeholder: |
        Example:
        - Update Gradle from 4.2.2 to 8.2.0
        - Update Kotlin from 1.7.20 to 1.9.22
        - Remove kotlin-android-extensions plugin
    validations:
      required: true
      
  - type: textarea
    id: checklist
    attributes:
      label: Task Checklist
      description: List of tasks to complete
      value: |
        - [ ] Task 1
        - [ ] Task 2
        - [ ] Task 3
    validations:
      required: true
      
  - type: textarea
    id: testing
    attributes:
      label: Testing Plan
      description: How will changes be tested?
      placeholder: |
        - Build debug APK
        - Test on Android 14 device
        - Test on Android 9 device
        - Verify all features work
    validations:
      required: false
      
  - type: textarea
    id: references
    attributes:
      label: References
      description: Links to relevant documentation
      placeholder: |
        - [CRITICAL_FIXES.md](../../CRITICAL_FIXES.md)
        - [UPGRADE_SUGGESTIONS.md](../../UPGRADE_SUGGESTIONS.md)
        - Android Developer Docs: https://developer.android.com/
    validations:
      required: false
      
  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      description: Any other relevant information
    validations:
      required: false
